services:
  web:
    build: ./web
    platform: linux/amd64
    container_name: vuln-web
    ports:
      - "8080:80"
    volumes:
      - ./web/vuln-app:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db
    networks:
      - vuln-net

  db:
    image: mysql:5.7
    container_name: vuln-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vuln-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vuln-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - vuln-net

networks:
  vuln-net:
    driver: bridge

volumes:
  db_data:
